### ISSUE TITLE
Make game_handler work using zulip_terminal

### ISSUE THREAD

**Issue by amanagr** [zulip/python-zulip-api#315]
Currently **tictactoe** and **connect_fout** bots are not working using the `zulip_terminal <bot-name>` method.
It raises following error for `$ zulip_terminal tictactoe`:
```
Traceback (most recent call last):
  File "/home/a/python-zulip-api/zulip-api-py3-venv/bin/zulip-terminal", line 11, in <module>
    load_entry_point('zulip-bots', 'console_scripts', 'zulip-terminal')()
  File "/home/a/python-zulip-api/zulip_bots/zulip_bots/terminal.py", line 57, in main
    message_handler.initialize(bot_handler)
  File "/home/a/python-zulip-api/zulip_bots/zulip_bots/game_handler.py", line 137, in initialize
    self.email = self.bot_handler.email
AttributeError: 'TerminalBotHandler' object has no attribute 'email'
```

**Comment by roberthoenig** [comment]
Thanks for the report @amanagr!
