### ISSUE TITLE
mercurial zulip-changegroup.py hook fails when importing zulip

### ISSUE THREAD

**Issue by scottrus** [zulip/python-zulip-api#322]
Tested on Python 2.7.x with Mercurial 4.5 and python-zulip-api 0.4.1

```
(zulip)[srussell@ln70-srussell zulip]$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
certifi (2018.1.18)
chardet (3.0.4)
idna (2.6)
mercurial (4.5)
pip (9.0.1)
requests (2.18.4)
setuptools (38.5.1)
six (1.11.0)
typing (3.6.4)
urllib3 (1.22)
zulip (0.4.1)
zulip-bots (0.4.0)
```

here is the traceback

```
(zulip)[srussell@ln70-srussell workdir]$ hg push
pushing to /var/apps/zulip/test
searching for changes
remote has heads on branch 'default' that are not known locally: 5883404cde47
adding changesets
adding manifests
adding file changes
added 1 changesets with 1 changes to 1 files
loading changegroup.zulip hook failed:
** unknown exception encountered, please report by visiting
** https://mercurial-scm.org/wiki/BugTracker
** Python 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
** Mercurial Distributed SCM (version 4.5)
** Extensions loaded: fetch, graphlog, record, transplant, children, purge, histedit, rebase, strip, mq, extdiff, shelve
Traceback (most recent call last):
  File "/var/apps/zulip/bin/hg", line 41, in <module>
    dispatch.run()
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 88, in run
    status = (dispatch(req) or 0) & 255
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 183, in dispatch
    ret = _runcatch(req)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 324, in _runcatch
    return _callcatch(ui, _runcatchfunc)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 332, in _callcatch
    return scmutil.callcatch(ui, func)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/scmutil.py", line 154, in callcatch
    return func()
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 314, in _runcatchfunc
    return _dispatch(req)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 918, in _dispatch
    cmdpats, cmdoptions)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 673, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 926, in _runcommand
    return cmdfunc()
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/dispatch.py", line 915, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/util.py", line 1195, in check
    return func(*args, **kwargs)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/util.py", line 1195, in check
    return func(*args, **kwargs)
  File "/var/apps/zulip/lib64/python2.7/site-packages/hgext/mq.py", line 3583, in mqcommand
    return orig(ui, repo, *args, **kwargs)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/util.py", line 1195, in check
    return func(*args, **kwargs)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/commands.py", line 4193, in push
    opargs=opargs)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/exchange.py", line 482, in push
    _pushbundle2(pushop)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/exchange.py", line 1041, in _pushbundle2
    stream, ['force'], pushop.remote.url())
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/localrepo.py", line 237, in unbundle
    ret = exchange.unbundle(self._repo, cg, heads, 'push', url)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/exchange.py", line 2016, in unbundle
    lockmod.release(lockandtr[2], lockandtr[1], lockandtr[0])
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/lock.py", line 329, in release
    lock.release()
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/lock.py", line 322, in release
    callback()
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/changegroup.py", line 399, in runhooks
    repo.hook("changegroup", **pycompat.strkwargs(hookargs))
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/localrepo.py", line 827, in hook
    return hook.hook(self.ui, self, name, throw, **args)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/hook.py", line 210, in hook
    res = runhooks(ui, repo, htype, hooks, throw=throw, **args)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/hook.py", line 254, in runhooks
    mod = extensions.loadpath(path, 'hghook.%s' % hname)
  File "/var/apps/zulip/lib64/python2.7/site-packages/mercurial/extensions.py", line 83, in loadpath
    return imp.load_source(module_name, path)
  File "/var/apps/zulip/zulip-changegroup.py", line 33, in <module>
    from typing import Any, Optional, Text
  File "/var/apps/zulip/lib64/python2.7/site-packages/hgdemandimport/demandimportpy2.py", line 243, in _demandimport
    level=level)
  File "/var/apps/zulip/lib64/python2.7/site-packages/hgdemandimport/demandimportpy2.py", line 41, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
  File "/var/apps/zulip/lib64/python2.7/site-packages/typing.py", line 1462, in <module>
    class Callable(object):
  File "/var/apps/zulip/lib64/python2.7/site-packages/typing.py", line 1474, in Callable
    __extra__ = collections_abc.Callable
  File "/var/apps/zulip/lib64/python2.7/site-packages/hgdemandimport/demandimportpy2.py", line 145, in __getattr__
    self._load()
  File "/var/apps/zulip/lib64/python2.7/site-packages/hgdemandimport/demandimportpy2.py", line 90, in _load
    mod = _hgextimport(_origimport, head, globals, locals, None, level)
  File "/var/apps/zulip/lib64/python2.7/site-packages/hgdemandimport/demandimportpy2.py", line 41, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
ValueError: Attempted relative import in non-package
```

**Comment by scottrus** [comment]
The fix I have is to import mercurial first and disable demandimport. There are some minor fixes needed in get_config() to handle optional config values like `branches`, `ignore_branches`, and `web_url`. Finally the summary contains the wrong `rev` number for the `changeset` as it's off by one. 

Maybe those other things should be separate issues? For now I'll make a PR to fix all three things and request it reviewed.

**Comment by roberthoenig** [comment]
Thanks for reporting this @scottrus! Left some comments on your PR.

**Comment by novokrest** [comment]
The main problem is that `typing` module is not defined in Python 2.7. 
From the above stacktrace:
```
  File "/var/apps/zulip/zulip-changegroup.py", line 33, in <module>
    from typing import Any, Optional, Text
```
That's why hook fails. I added [PR](https://github.com/zulip/python-zulip-api/pull/393) with simple fix.

**Comment by timabbott** [comment]
Sidenote @novokrest -- do you know why this had such a weird traceback?

**Comment by novokrest** [comment]
@timabbott The traceback is a little weird because Mercurial imports modules by custom implementation of module's loader (defined in `demandimport2.py`). As can be seen from the traceback, there is error `ValueError: Attempted relative import in non-package`.  It is raised because we *don't* specify our changegroup's hook in `.hg/hgrc` *as module* (according  ) but rather as path to python file. 

I propose the following solution for this issue:
- add changegroup's hook to `PYTHONPATH` (we should remove dashes from file's name, so, for example, rename file to `zulip_changegroup.py`
- define changegroup's hook as `changegroup = python:zulip_changegroup.hook`
- update changegroup's hook implementation according to current mercurial API.

P.S. I updated [#P393](https://github.com/zulip/python-zulip-api/pull/393) according to above proposed solution.
