### ISSUE TITLE
tools/provision error with python3.6.7rc1

### ISSUE THREAD

**Issue by ujjwalrox** [zulip/python-zulip-api#482]
Script is unable to convert this version to int.

```
Traceback (most recent call last):
  File "tools/provision", line 119, in <module>
    main()
  File "tools/provision", line 39, in main
    py_version = tuple(int(num) for num in py_version_list)
  File "tools/provision", line 39, in <genexpr>
    py_version = tuple(int(num) for num in py_version_list)
ValueError: invalid literal for int() with base 10: '7rc1'
```

**Comment by ujjwalrox** [comment]
@zulipbot claim

**Comment by ujjwalrox** [comment]
@zulipbot claim
